### ISSUE TITLE
Edit Posts fonts & sizes

### ISSUE THREAD

**Issue by dtpbr** [godaddy/wp-escapade-theme#53]
How do I reduce the font size of the Posts page? I have a blog page, but the summary page listing all the posts (along with the actual individual posts) has too large of fonts. It is actually hard to read they are so big. How can I manage the headings sizes and body sizes please?

**Comment by EvanHerman** [comment]
Hi @dtpbr ,

While there are no controls built into the theme to allow you to control the font size, you can do so using some custom CSS.

First you will want to open up the customizer. You can do so from the dashboard by heading into 'Appearance > Customize'.

Once inside of the customizer, you will want to click on 'Additional CSS' at the bottom.

You can enter the following CSS snippet into this section to adjust the font size for the body.

```css
body #content p {
   font-size: 18px;
}
```

**Note:** You can tweak it to your liking by altering the 18px font size in the snippet above.

You may also want to get a little more granular in the fonts that you are adjusting, since the above is going to target all paragraph (`<p>`) elements inside of the main content of your site. But that should be a solid starting point for you to work with.

Evan
